main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

story7/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story7/',include('story7app.urls'), name='story7app'),
    path('story8/',include('story8.urls'), name='story8'),
    path('story9/',include('story9.urls'), name='story9'),
]

story7app/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'story7app'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.activities, name='activities'),
]

story8/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.books, name='books'),
    path('data/', views.data, name='data'),
]

story9/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
]

main/models.py
from django.db import models

# Create your models here.

story7app/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html')

story7app/views.py
from django.shortcuts import render

# Create your views here.
def activities(request):
    return render(request, 'activities.html')

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json

# Create your views here.
def books(request):
    return render(request, 'books.html')

def data(request):
    getdata = requests.get('https://www.googleapis.com/books/v1/volumes?q=' + request.GET['q'])
    jsondata = json.loads(getdata.content)
    return JsonResponse(jsondata, safe=False)

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

# Create your views here.
def home(request):
    return render(request, 'home.html')

def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        if User.objects.filter(username=username).exists():
            messages.error(request, "username is already taken, please use another name")
        else:
            user = User.objects.create_user(username,email,password)
            return redirect ('/story9/signin/')
    return render(request, 'signup.html')

def signin(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        if User.objects.filter(username=username).exists():
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/story9/')
            else:
                messages.error(request, "Invalid password, please check it again")
        else:
            messages.error(request, "username is not exist, please check or sign up an account")
    return render(request, 'login.html')

def signout(request):
    logout(request)
    return redirect('/story9/')

main/templates/main/home.html
{% extends 'base.html'%}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html>
    <head>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>
        Welcome!
    </title>
    </head>
    <body>
        <div class="container">
            <div class="jumbotron">
                <h1 class="display-4" style="text-align: center; overflow-wrap: break-word;">Welcome!</h1>
                <hr class="my-4">
                <p class="lead">
                  <a class="btn btn-primary btn-lg" href="{% url 'story7app:activities' %}" role="button">See What I'm Up To</a>
                  <a class="btn btn-primary btn-lg" href="{% url 'story8:books' %}" role="button">Books Lists</a>
                </p>
              </div>
        </div>
    </body>
</html>

{% endblock content %}

story7app/templates/activities.html
{% extends 'base.html'%}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html>
    <head>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <title>
          My Activities
      </title>
      <script src="{% static 'script.js' %}"></script>
    </head>
    <body>
      <div class="container" style="width: 100%;">
        <h1 class="titles overflow-auto">What I've Been Up To</h1>
          <div class="accordion">
            <div class="textaccordion" id="aktivitas">
              <h3>
                Aktivitas Saat Ini
                <div class="float-right">
                <button type="button" class="upbutton">^</button>
                <button type="button" class="downbutton">v</button>
                </div>
              </h3>
              <div>
                On Repeat:
                <ul>
                  <li>
                    Kuliah
                  </li>
                  <li>
                    Nugas
                  </li>
                  <li>
                    Rapat
                  </li>
                  <li>
                    Makan
                  </li>
                  <li>
                    Tidur
                  </li>
                </ul>
              </div>
            </div>
            <div id="kepanitiaan">
              <h3>
                Kepanitiaan dan Organisasi
                <div class="float-right">
                  <button type="button" class="upbutton">^</button>
                  <button type="button" class="downbutton">v</button>
                </div>
              </h3>
              <div>
                Yang Sudah Selesai :
                <ul>
                  <li>
                    Staf Editorial Marketing COMPFEST 12
                  </li>
                  <li>
                    Staf Relasi Wisuda Genap 2020
                  </li>
                  <li>
                    Mentor OKK UI 2020
                  </li>
                </ul>
                Yang Masih Berjalan :
                <ul>
                  <li>
                    Staf Departemen Adkesma BEM Fasilkom UI 2020
                  </li>
                </ul>
              </div>
            </div>
            <div id="prestasi">
              <h3>
                Prestasi
                <div class="float-right">
                  <button type="button" class="upbutton">^</button>
                  <button type="button" class="downbutton">v</button>
                </div>
              </h3>
              <div>
                <ul>
                  <li>Lomba Tata Upacara Bendera SMAN 40 Jakarta</li>
                  <li>Nilai 100 UN SMA Mata Pelajaran Bahasa Indonesia</li>
                </ul>
              </div>
            </div>
            <div id="hobi">
              <h3>
                Hobi dan Yang Dilakukan Selain Kuliah
                <div class="float-right">
                  <button type="button" class="upbutton">^</button>
                  <button type="button" class="downbutton">v</button>
                </div>
              </h3>
              <div>
                <ul>
                  <li>
                    Menonton Drama dan Variety Shows<br>
                    On-going drama yang sedang ditonton = Penthouse, Live On, The Gifted Graduation<br>
                    On-going variety shows yang sedang ditonton = New Journey To The West Season 8, 2 Days 1 Night Season 4
                  </li>
                  <li>
                    Mendengarkan Musik + Fangirling<br>
                    Current favorite music = ONF - Moscow Moscow, Treasure - Orange, Weeekly - Zig Zag <br>
                    Favorite groups = AB6IX, ONF, Treasure, Weeekly<br>
                  </li>
                  <li>
                    Membaca Novel (On Hiatus)<br>
                    Favorite series = The Hunger Games, The Mortal Instruments
                  </li>
                </ul>
              </div>
            </div>
          </div>
      </div>
    </body>
</html>
{% endblock content %}

story8/templates/books.html
{% extends 'base.html'%}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html>
    <head>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <title>
        List of Books
      </title>
      <script src="{% static 'search.js' %}"></script>
    
    </head>
    <body>
      <div class="container" style="width: 100%;">
        <h1 class="titles overflow-auto">Search Any Books</h1>
        <div class="input" style="display: flex; flex-flow: row wrap;">
          <input class="form-control" type="text" id="search" placeholder="Search books here">
        </div>
        <br>
        <div style="display: flex; overflow-x:auto;">
            <table class="table table-borderless">
                <thead>
                    <tr>
                        <th class="align-middle">No</th>
                        <th class="align-middle">Cover</th>
                        <th class="align-middle">Title</th>
                        <th class="align-middle">Author(s)</th>
                        <th class="align-middle">Publisher</th>
                        <th class="align-middle">Released date</th>
                    </tr>
                </thead>
                <tbody id="hasil"></tbody>
            </table>
        </div>
      </div>
    </body>
</html>
{% endblock content %}

story9/templates/home.html
{% load static %}
{% block content %}

<!DOCTYPE html>
<html>
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">   
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <title>
        Welcome!
      </title>
    
    </head>
    <body>
      <div class="container">
        <div class="jumbotron jumbotron-fluid">
          {% if user.is_authenticated %}
          <h1 class="display-4" style="text-align: center; overflow-wrap: break-word;">Welcome, {{ user.username }}</h1>
          <div style="width: 100%; text-align: center;">
            <h2 style="overflow-wrap: break-word;">log out</h2>
            <a class="btn btn-primary btn-lg" href="{% url 'story9:signout' %}" role="button">Logout</a>
          </div>
          {% else %}
          <h1 class="display-4" style="text-align: center; overflow-wrap: break-word;">Welcome, Guest</h1>
          <hr class="my-4">
          <div class="d-flex flex-row flex-wrap" style="overflow: scroll;">
            <div class="overflow-auto" style="width: 50%; text-align: center;">
              <h2 style="overflow-wrap: break-word;">log in to existing account</h2>
              <a class="btn btn-primary btn-lg" href="{% url 'story9:signin' %}" role="button">Login</a>
            </div>
            <div class="overflow-auto" style="width: 50%; text-align: center;">
              <h2 style="overflow-wrap: break-word;">create new account</h2>
              <a class="btn btn-primary btn-lg" href="{% url 'story9:signup' %}" role="button">Sign Up</a>
            </div>
          </div>
          {% endif %}
        </div>
      </div>
    </body>
</html>
{% endblock content %}

story9/templates/login.html
{% load static %}
{% block content %}

<!DOCTYPE html>
<html>
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">   
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <title>
        Login
      </title>
    
    </head>
    <body>
      <div class="container" style="width: 100%;">
        <h1 class="titles overflow-auto">Login</h1>
        {% if messages %}
        {% for message in messages %}
        <p {% if message.tags %} class="{{ message.tags }}"{% endif %} style="color: red; overflow-wrap: break-word;"><b>{{ message }}</b></p>
        {% endfor %}
        {% endif %}
        {% if user.is_authenticated %}
        <p style="overflow-wrap: break-word;">You have already logged in!</p>
        <a href="{% url 'story9:home' %}" class="btn btn-primary btn-lg">Back to Home</a>
        {% else %}
        <form method="POST" style="border: cornflowerblue; border-style:dotted; padding: 2%; overflow-wrap: break-word;">
          {% csrf_token %}
          <div class="form-group">
            <label>Username</label>
            <input required type="text" name="username" class="form-control" id="username">
          </div>
          <div class="form-group">
            <label>Password</label>
            <input required type="password" name="password" class="form-control" id="password">
          </div>
          <button type="submit" class="btn btn-outline-success">Submit</button>
        </form>
        <div style="margin-top: 2%;">Create new account</div>
        <a class="btn btn-primary" href="{% url 'story9:signup' %}" role="button">Sign Up</a>  
        <div style="margin-top: 2%;">Back to home</div>
        <a href="{% url 'story9:home' %}" class="btn btn-primary">Home</a> 
        {% endif %}
      </div>
    </body>
</html>
{% endblock content %}

story9/templates/signup.html
{% load static %}
{% block content %}

<!DOCTYPE html>
<html>
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">   
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <title>
        Sign Up
      </title>
    
    </head>
    <body>
      <div class="container" style="width: 100%;">
        <h1 class="titles overflow-auto">Sign Up</h1>
        {% if messages %}
        {% for message in messages %}
        <p {% if message.tags %} class="{{ message.tags }}"{% endif %} style="color: red;"><b>{{ message }}</b></p>
        {% endfor %}
        {% endif %}

        {% if user.is_authenticated %}
        <h2>Hello, {{user.username}}</h2>
        <p>You have already logged in!</p>
        <p>Log out first to make a new account</p>
        <a href="{% url 'story9:home' %}" class="btn btn-primary btn-lg">Back to Home</a>
        {% else %}
        <form method="POST" style="border: cornflowerblue; border-style:dotted; padding: 2%;">
          {% csrf_token %}
          <div class="form-group">
            <label>Email address</label>
            <input required type="text" name="email" class="form-control" id="email">
          </div>
          <div class="form-group">
            <label>Username</label>
            <input required type="text" name="username" class="form-control" id="username">
          </div>
          <div class="form-group">
            <label>Password</label>
            <input required type="password" name="password" class="form-control" id="password">
          </div>
          <button type="submit" class="btn btn-outline-success">Submit</button>
        </form>
        <div style="margin-top: 2%;">Log in to your account</div>
        <a class="btn btn-primary" href="{% url 'story9:signin' %}" role="button">Login</a> 
        <div style="margin-top: 2%;">Back to home</div>
        <a href="{% url 'story9:home' %}" class="btn btn-primary">Home</a> 
        {% endif %}
      </div>
    </body>
</html>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <header>
      <nav class="navbar navbar-expand-lg navbar-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">  
          <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link" href="/">Home</a>
              </li> 
              <li class="nav-item">
                <a class="nav-link" href="{% url 'story7app:activities' %}">My Activities</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'story8:books' %}">List of Books</a>
              </li>
            </ul>
        </div>
      </nav>
  </header>

  
  {% block content %}
  {% endblock content %}
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <!-- block for js and jquery accordion -->
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</body>
</html>